[package]
name = "Rust_Study"
version = "0.1.0"
authors = ["lzw <657434763@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"